# Nombre del workflow para tu proyecto de frontend
name: React CI

# Se ejecuta con cada push o pull request a la rama main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    # Se ejecuta en una m치quina virtual con Ubuntu// en que sistema operativo debe ejecutrase este proyecto 
    runs-on: ubuntu-latest

    steps:
      # 1. Descarga tu c칩digo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Instala Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # 3. Instala las dependencias del proyecto
      - name: Install dependencies
        run: npm install

      # 4. Ejecuta las pruebas (si las tienes configuradas)
      - name: Run tests
        run: npm test

      # 5. Crea una versi칩n de producci칩n para verificar que no hay errores
      - name: Build for production
        run: npm run build