# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test:
    # El tipo de máquina virtual donde se ejecutará
    runs-on: ubuntu-latest

    # Pasos que se ejecutarán en secuencia
    steps:
      # 1. Descarga el código del repositorio en el runner
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Instala Node.js para que esté disponible en los siguientes pasos
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # O la versión que uses en tu proyecto

      # --- Pasos para el Backend (Node.js) ---
      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      - name: Run backend tests
        run: npm test
        working-directory: ./backend

      # --- Pasos para el Frontend (React) ---
      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run frontend tests
        run: npm test
        working-directory: ./frontend
      
      - name: Build frontend for production check
        run: npm run build
        working-directory: ./frontend