# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test:
    # Se ejecuta en una m치quina virtual con Ubuntu
    runs-on: ubuntu-latest

    steps:
      # 1. Descarga tu c칩digo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Instala Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # 3. Instala las dependencias del proyecto
      - name: Install dependencies
        run: npm install

      # 4. Ejecuta las pruebas (si las tienes configuradas)
      #- name: Run tests
      #  run: npm test

      # 5. Crea una versi칩n de producci칩n para verificar que no hay errores
      - name: Build for production
        run: npm run build